### ISSUE TITLE
RuntimeError: Unknown model (vim_tiny_patch16_224_bimambav2_final_pool_mean_abs_pos_embed_with_midclstok_div2)

### ISSUE THREAD

**Issue by talrub** [hustvl/Vim#104]
Hi,
I am trying to load  'vim_tiny_patch16_224_bimambav2_final_pool_mean_abs_pos_embed_with_midclstok_div2' for inference the same way you did in main.py:

from timm.models import create_model

nb_classes = 1000
drop = 0
drop_path= 0.0
input_size = 224
model = create_model(
    'vim_tiny_patch16_224_bimambav2_final_pool_mean_abs_pos_embed_with_midclstok_div2',
    pretrained=False,
    num_classes=nb_classes,
    drop_rate=drop,
    drop_path_rate=drop_path,
    drop_block_rate=None,
    img_size=input_size,
)

But for some reason i am getting the following error:

RuntimeError: Unknown model (vim_tiny_patch16_224_bimambav2_final_pool_mean_abs_pos_embed_with_midclstok_div2)

Can you please advise?

**Comment by Where-The-Willows-Grow** [comment]
I have the same issue . Could you please tell me how to solve it?
