### ISSUE TITLE
I get a error "TypeError: Mamba.__init__() got an unexpected keyword argument 'if_devide_out'"

### ISSUE THREAD

**Issue by Otakus0320** [hustvl/Vim#118]
I have already copy mamba-1p1p1/mamba_ssm to /root/miniconda3/lib/python3.12/site-packages/
but I still get this problem
how can i solve it

**Comment by CrazyGeG** [comment]
Hi,
How did you fix this error?

**Comment by hjh695** [comment]
Have you solved it ?  I meet the same problem

**Comment by ZhanYang-nwpu** [comment]
> I have already copy mamba-1p1p1/mamba_ssm to /root/miniconda3/lib/python3.12/site-packages/ but I still get this problem how can i solve it

Have you solved it ? I meet the same problem

**Comment by Otakus0320** [comment]
nope

**Comment by Liangzhanbo** [comment]
[https://github.com/hustvl/Vim/issues/124](url)
