### ISSUE TITLE
Mamba Tokenizer loading from a hard coded path

### ISSUE THREAD

**Issue by vaibhavBh-0** [hustvl/Vim#2]
https://github.com/hustvl/Vim/blob/5c3d4ad4b56934740fe0cb8736f3381cbe8091df/mamba/benchmarks/benchmark_generation_mamba_simple.py#L36

Edit: 
Is the tokenizer used different from the one below?
` tokenizer = AutoTokenizer.from_pretrained("EleutherAI/gpt-neox-20b")`

**Comment by Unrealluver** [comment]
Hi ! vaibhavBh-0,

You just need to install `mamba` which provides the bidirectional mamba implementation. The scripts for benchmarking are not used here. :)
