### ISSUE TITLE
pip install -e mamba

### ISSUE THREAD

**Issue by innocence0206** [hustvl/Vim#20]
I got **error: namespace "cub" has no member "WarpMask"** when installing the mamba, but I have no idea how to solve it, could you give me some advice? Thanks

**Comment by xuanhu001** [comment]
I met the same problem when I ran `pip install -e mamba-1p1p1` in Vim. This is error log.
```log
Vim/mamba-1p1p1/csrc/selective_scan/reverse_scan.cuh(120): error: namespace "cub" has no member "WarpMask"
              detected during:
                instantiation of "void BlockReverseScan<T, BLOCK_DIM_X, MEMOIZE>::ExclusiveReverseScan(T, T &, ScanOp, BlockPostfixCallbackOp &) [with T=float4, BLOCK_DIM_X=32, MEMOIZE=false, ScanOp=SSMScanOp<complex_t>, BlockPostfixCallbackOp=SSMScanPrefixCallbackOp<complex_t>]"
```
Could you share how to solve it? Thank you in advance for your time and assistance.
