### ISSUE TITLE
pretraining.sh launch script is hardcoded to dev folders/env...can you provide a generic launch script for regular servers?

### ISSUE THREAD

**Issue by lessw2020** [hustvl/Vim#5]
Can you provide a generic launch script for pre-training with vim?
The readme suggests to run:
bash vim/scripts/pt-vim-t.sh

but the contents of pt-vimt-t.sh have a bunch of local hardcoded paths that do not exist on regular servers ala:
--data-path /share/project/lianghuizhu/datasets/IN1K
source /opt/conda/bin/activate /home/zhulianghui/.conda/envs/deit-dev
etc.

Thanks very much.

**Comment by Unrealluver** [comment]
Greetings!

Thanks for your suggestion! We have fixed it.

**Comment by lessw2020** [comment]
Thanks very much for the fast fix!
