### ISSUE TITLE
Flipped Residual Connection

### ISSUE THREAD

**Issue by AliYoussef97** [hustvl/Vim#71]
Hello,

Thank you for your amazing work!

From the paper, the last line in the Vim Alogirthim is as follows:
$T_l$ : (B, M, D) ← $Linear^T$ ( $y_{forward}$ + $y_{backward}$ ) + $T_{l−1}$

From the code the backward process is the same as the forward, just the input sequence is flipped. However, the input token sequence (residual) is added to the forward+backward output, but should the flipped token sequence be added as an residual as well, such as:

$T_l$ : (B, M, D) ← $Linear^T$ ( $y_{forward}$ + $y_{backward}$ ) + $T_{l−1}$ + $T_{l−1 flipped}$

-------------------------

Edit:

I also noticed each "v2" Mamba block contains out_a and out_b, which is both forward and backward, but in the for loop [here](https://github.com/hustvl/Vim/blob/6143d07b3dd31f904c63840a19e22d95d1124493/vim/models_mamba.py#L483C13-L496C61), we process two Mamba blocks at the same time, each has its out out_a and out_b, but the input for the second Mamba Block is flipped, which is qutie confusing, does that mean the flipped input for the second Mamba Block is not related to Mamba Block itself and mroe of a training mechanisim? Meaning, if the for loop processes one layer at a time, wouldn't a Mamba Block do a forward and backward SSM pass?

Thank you!

**Comment by jsrdcht** [comment]
> I also noticed each "v2" Mamba block contains out_a and out_b, which is both forward and backward, but in the for loop [here](https://github.com/hustvl/Vim/blob/6143d07b3dd31f904c63840a19e22d95d1124493/vim/models_mamba.py#L483C13-L496C61), we process two Mamba blocks at the same time, each has its out out_a and out_b, but the input for the second Mamba Block is flipped, which is qutie confusing, does that mean the flipped input for the second Mamba Block is not related to Mamba Block itself and mroe of a training mechanisim? Meaning, if the for loop processes one layer at a time, wouldn't a Mamba Block do a forward and backward SSM pass?

From my understanding, the addition of an extra reverse scan for the Vision Mamba is a compromise by the author due to it not being a natural temporal signal. The term "flipped input for the second Mamba Block" refers to this reverse scanning process, while reusing the same block code.

What's truly confusing is the uncertainty surrounding the input and output of the Vision Mamba block. The descriptions in the code seem to contradict those in the paper. The paper mentions two linear transformation layers in the front part of the block (corresponding to lines 3 and 4 of Algorithm 1), but there is no corresponding implementation in the code. If you understand this clearly, perhaps we can discuss it further.

Lastly, the implementation of fused_add_and_norm by the author also adds complexity to understanding the code.

**Comment by jsrdcht** [comment]
> I also noticed each "v2" Mamba block contains out_a and out_b, which is both forward and backward, but in the for loop [here](https://github.com/hustvl/Vim/blob/6143d07b3dd31f904c63840a19e22d95d1124493/vim/models_mamba.py#L483C13-L496C61), we process two Mamba blocks at the same time, each has its out out_a and out_b, but the input for the second Mamba Block is flipped, which is qutie confusing, does that mean the flipped input for the second Mamba Block is not related to Mamba Block itself and mroe of a training mechanisim? Meaning, if the for loop processes one layer at a time, wouldn't a Mamba Block do a forward and backward SSM pass?

I found the same problem, kick me if you find sth. else

**Comment by AliYoussef97** [comment]
@jsrdcht [`if_bidirectional`](https://github.com/hustvl/Vim/blob/6143d07b3dd31f904c63840a19e22d95d1124493/vim/models_mamba.py#L247C18-L247C34) is set as `False` and  [`flip_img_sequences_ratio`](https://github.com/hustvl/Vim/blob/6143d07b3dd31f904c63840a19e22d95d1124493/vim/models_mamba.py#L252) is set as `-1`, thus, the input is process normally as forward and backward "v2" [here](https://github.com/hustvl/Vim/blob/6143d07b3dd31f904c63840a19e22d95d1124493/vim/models_mamba.py#L459C9-L480C18). Hope that helps!

**Comment by jsrdcht** [comment]
> @jsrdcht [`if_bidirectional`](https://github.com/hustvl/Vim/blob/6143d07b3dd31f904c63840a19e22d95d1124493/vim/models_mamba.py#L247C18-L247C34) is set as `False` and [`flip_img_sequences_ratio`](https://github.com/hustvl/Vim/blob/6143d07b3dd31f904c63840a19e22d95d1124493/vim/models_mamba.py#L252) is set as `-1`, thus, the input is processed normally as forward and backward "v2" [here](https://github.com/hustvl/Vim/blob/6143d07b3dd31f904c63840a19e22d95d1124493/vim/models_mamba.py#L459C9-L480C18). Hope that helps!

Thanks a lot! I think you are right. However, there is still one issue about the depth of the model. 
Why the default depth is [24](https://github.com/hustvl/Vim/blob/f6bc574854a23bbd97a4a4901445a88a192713ef/vim/models_mamba.py#L1019) in the sense of small/tiny model if it's not for _bidirection_? I mean, considering the ViT/small sets it to 12.

**Comment by AliYoussef97** [comment]
@jsrdcht The model itself is bidirectional, and can be found [here](https://github.com/hustvl/Vim/blob/f6bc574854a23bbd97a4a4901445a88a192713ef/mamba-1p1p1/mamba_ssm/modules/mamba_simple.py#L215C16-L246C134). The [`if_bidirectional`](https://github.com/hustvl/Vim/blob/6143d07b3dd31f904c63840a19e22d95d1124493/vim/models_mamba.py#L247C18-L247C34)  parameter being `False` just ensures that we do not use this [loop](https://github.com/hustvl/Vim/blob/f6bc574854a23bbd97a4a4901445a88a192713ef/vim/models_mamba.py#L947C9-L962C61). So with `if_bidirectional` being `False` and `flip_img_sequences_ratio` as `-1`, the input is fed [here](https://github.com/hustvl/Vim/blob/f6bc574854a23bbd97a4a4901445a88a192713ef/vim/models_mamba.py#L944C17-L946C18) directly, which goes to `v2` (the first link in this comment). The small and tiny do not differ in depth, but differ in the hidden state dimension (3.4. Architecture Details in the paper).

**Comment by jsrdcht** [comment]
@AliYoussef97 Yeah, I agree with you. 

>The small and tiny do not differ in depth, but differ in the hidden state dimension (3.4. Architecture Details in the paper).

That's not my point. Based on what you just mentioned, so each Vision Mamba block implements both forward and backward modules internally, can we simply compare each mamba block to a transformer block?

In the configuration of vision transformer small, the depth is `12` (possibly even lower), while for vision mamba it is set to `24`. Assuming `if_bidirectional` is `True`, `24` can be interpreted as having two types of blocks. How should we understand this default parameter of `24` if `if_bidirectional` is `False`?

**Comment by AliYoussef97** [comment]
@jsrdcht The linked repo is not the official implementation, thus I am not quite sure why the depth is 12, but by default, the paper states the difference is in the Hidden state dimension. `if_bidirectional ` is related to the ablation study in the paper, and should be `False` from my understanding.
