### ISSUE TITLE
Could you please provide your pretrained model for validation soon？

### ISSUE THREAD

**Issue by Cynicarlos** [hustvl/Vim#8]
Dear authors:
Hope this issue finds you well!
It seems that I can not get your results without your pretrained model. The url in the following figure is 'to.do', so I hope that the pretrained model will be seen soon.Thanks!
![image](https://github.com/hustvl/Vim/assets/77565463/7a065a3f-7d30-48b1-8a21-250a83cc18c8)

**Comment by Unrealluver** [comment]
Hi, 

We have updated the `Readme.md` and you can find the released checkpoint in it~
