### ISSUE TITLE
Difference between the checkpoints?

### ISSUE THREAD

**Issue by jiabingxiing** [hustvl/Vim#81]
Dear authors:
Thanks for your work!
I am curious about the difference between the different checkpoints you provide and would like to get your answer:
![PixPin_2024-05-13_15-58-04](https://github.com/hustvl/Vim/assets/54266673/a5179527-e674-4026-b32f-6767dc3f830c)
you provided 2 checkpoints and they are of different sizes

**Comment by BranStarkkk** [comment]
第二个带“ft”的是微调过的，第一个性能相对差一些

**Comment by xiaridehehe** [comment]
我想请问一些，这个训练连权重是在哪里下载的呀

**Comment by BranStarkkk** [comment]
> 我想请问一些，这个训练连权重是在哪里下载的呀

hugging face搜vim

**Comment by jiabingxiing** [comment]
> 第二个带“ft”的是微调过的，第一个性能相对差一些

Thanks for your reply!
