### ISSUE TITLE
import causal_conv1d_cuda出现错误

### ISSUE THREAD

**Issue by NakrAi** [hustvl/Vim#91]
![2bae3d39ac577424f538806486bf480](https://github.com/hustvl/Vim/assets/152459373/e049f93e-0c7b-4e36-9114-60a6039b191a)
![181d25b163f77ba74f3a63807a034a2](https://github.com/hustvl/Vim/assets/152459373/fc0f4c20-7cbf-4d7b-aef7-2f81c9309c33)

import causal_conv1d_cuda请问这里报错是为什么啊？

**Comment by yanyu369** [comment]
同问，请问解决了吗
